[package]
name = "passworstlib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base16ct = { version = "0.2.0", features = ["alloc"] }
base64 = "0.22.1"
jni = "0.21.1"
sha2 = "0.10.6"

[lib]
crate-type = ["cdylib"]

